### ISSUE TITLE
Joystick Breaks Keyboard

### ISSUE THREAD

**Issue by kristiana-rendon** [BCLab-UNM/SwarmBaseCode-ROS#118]
When the joystick is plugged into the laptop, the keyboard manual control stops working. The rover moves in jerking motions and is not very responsive. The joystick controller, however, works.

**Comment by JCHJones** [comment]
This is not a bug, fixing this would be a feature enhancement. Primary reason it shouldn't be done

Joystick commands override keyboard commands and in order to not have that happen logic would have to be added to intelligently determine which system the user is trying to use and switch to only accepting commands from that system until such a time as its determine the user wants to use the other system. Also due to the nature of such logic commands from both systems at once would not work nor would rapidly switching between them work and I see of no reason to need such a feature.

This along with the fact that keyboard commands are only there as a courtesy and really all manual control was intended to be exclusively joystick control leads me to believe that this should not be changed.
