### ISSUE TITLE
Pickup offset and jerk

### ISSUE THREAD

**Issue by JCHJones** [BCLab-UNM/SwarmBaseCode-ROS#60]
The alignment and timing of pickup is wrong often trying to grab to the right side of blocks. The distance driven and locking distance are also incorrect.

The second related problem and may be solved by the previous is the alignment jerking off to the right at the last second before a block is locked in.

**Comment by jschlind411** [comment]
Using Pull Request #75 sees rover driving straight and attempting to pick up cubes without too much jerking and twitching  However, the rover is not entering a specific state of pickup.

Issue with rover not entering this section of code in Pickup Controller:
 ```
   else if (blockDistance > targetDistance && !lockTarget) //if a target is detected but not locked, and not too close.
    {

      //NOT EVER REACHING THIS STATE
      //cout << "PICKUP Adjusting Heading/Driving Forward "<< std::endl;

      // this is a 3-line P controller, where Kp = 0.20
      float vel = blockDistance * 0.20;
      if (vel < 0.1) vel = 0.1;
      if (vel > 0.2) vel = 0.2;

      result.pd.cmdVel = vel;
      result.pd.cmdAngularError = -blockYawError;
      timeOut = false;
      nTargetsSeen = 0;
      return result;
    }
```

Using this cout statement before main logic is ran inside Result PickUpController::DoWork() after time values are set (Line 205)

`    cout << "PICKUP BLOCK DIST:  " << blockDistance << ", TARGET DISTANCE:  " << targetDistance << std::endl;`

will generate this output:

PICKUP BLOCK DIST:  1e-05, TARGET DISTANCE:  0.15

This, I believe, is due to issues with blockdDistance not being calculated correctly or due to another issue with the camera.

The net result is that the first block never is called to change the robots orientation to pick up the cube correctly.  This may fix several issues after it has been resolved.
