### ISSUE TITLE
Constant and Slow PID

### ISSUE THREAD

**Issue by JCHJones** [BCLab-UNM/SwarmBaseCode-ROS#61]
Both the const speed PID and the Slow speed PID are off on tuning with most notable problems being seen when obstacle avoiding causing a wagging jerk like motion as the robot turns away from obstacles.

**Comment by kristiana-rendon** [comment]
I don't think tuning the PIDs would fix this issue because the rover still needs to stop and check for obstacles, unless it can check for obstacles and turn at the same time. I tested some values with the PIDs and I was able to get a very smooth turn, but that's only when I changed the angle, but since the angle is static, it would have to keep turning if the obstacle was still within that turning angle.
